### PR TITLE
Cipher suite definitions

### PR DESCRIPTION
**Pull request by lchudinov**
### Cipher suite definitions
Linked issue: zowe/zlux#632

### CODE REVIEW

**Comment by ifakhrutdinov** [comment]
@lchudinov where can I get values to verify against? https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.gska100/csdcwh.htm ?

**Comment by lchudinov** [comment]
> @lchudinov where can I get values to verify against? https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.gska100/csdcwh.htm ?

@ifakhrutdinov Yes, https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.gska100/csdcwh.htm

**Review by ifakhrutdinov — COMMENTED** [review]
Not sure if you'd like to make these consistent with the source:

image

Yours is on the right.

**Comment by lchudinov** [comment]
@ifakhrutdinov Sorry, actually I copied the names from an older version https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.gska100/csdcwh.htm

**Comment by ifakhrutdinov** [comment]
@lchudinov will you update the PR? The newer names seem to be used all over the internet as oppose to what we have now.

**Comment by lchudinov** [comment]
@ifakhrutdinov  Updated

**Review by 1000TurquoisePogs — APPROVED** [review]

**Pull request merged**
