### PR TITLE
IDTA parameter in safverify

### PR DESCRIPTION
**Pull request by achmelo**

### CODE REVIEW

**Comment by ifakhrutdinov** [comment]
@achmelo you've got a typo in the title. DCO needs fixing.

**Comment by achmelo** [comment]
> @achmelo you've got a typo in the title. DCO needs fixing.

@ifakhrutdinov fixed

**Review by ifakhrutdinov — APPROVED** [review]
The diff is the same as in https://github.com/zowe/zowe-common-c/pull/289, but I'd make sure the functionality works as expected because there have been changes in v2 in zos.c, they've touched the code these changes rely on.

**Comment by achmelo** [comment]
> The diff is the same as in #289, but I'd make sure the functionality works as expected because there have been changes in v2 in zos.c, they've touched the code these changes rely on.

I've verified the functionality on our internal system and it was working as expected.

**Pull request merged**
