### PR TITLE
jesService c1

### PR DESCRIPTION
**Pull request by joepun76**
Signed-off-by: joepun76 <jouphpun76@gmail.com>

### CODE REVIEW

**Comment by joepun76** [comment]
This is the zowe-common-c portion of /jes endpoint to submit job.

**Comment by ifakhrutdinov** [comment]
@joepun76 I believe this should go into the zss repo. This is not common code. You may have thought that this belonged here because datasetsjson.c is in this repo, but we'd want to move it at some point in the future too.

CC: @1000TurquoisePogs

**Comment by joepun76** [comment]
@ifakhrutdinov Yes, that's what I thought. Another question - I need to use below 4 functions in datasetjson.c, therefore I removed the static in front of these 4 functions.  Is it the right way? or you would suggest another method.  Thanks very much.
int getLreclOrRespondError(HttpResponse *response, const DatasetName *dsn, const char *ddPath)
bool isDatasetPathValid(const char *path)
void extractDatasetAndMemberName(const char *datasetPath,
                                        DatasetName *dsn,
                                        DatasetMemberName *memberName)
void respondWithDYNALLOCError(HttpResponse *response,
                              int rc, int sysRC, int sysRSN,
                              const DynallocDatasetName *dsn,
                              const DynallocMemberName *member,
                              const char *site)

If yes, datasetjson.c needs to be updated in this PR.

Thanks again!

**Comment by ifakhrutdinov** [comment]
No, we don't need those functions to be public by exposing them via `datasetjson.c`.

I feel like, ideally, we'd want to move `datasetsjson.c` to zss, create some dsutils.c there or `zowe-common-c`, so your service and the data set services could share it. @1000TurquoisePogs perhaps this is the time to move it?

**Comment by joepun76** [comment]
@ifakhrutdinov ,
As agreed by @1000TurquoisePogs to move datasetjson.c to zss, will do dsutils.c in zss and move datasetjson.c to zss and jes modules in zss. This PR will be closed. Thanks.

**Pull request closed without merging**
