### PR TITLE
Support APPL keyword  for IDT token call

### PR DESCRIPTION
**Pull request by vit-tomica**
Signed-off-by: Vit Tomica <vit.tomica@broadcom.com>

### CODE REVIEW

**Comment by vit-tomica** [comment]
Hello @ifakhrutdinov @lchudinov, can you take a look at this PR, please?

**Review by lchudinov — APPROVED** [review]
Looks good to me

**Comment by ifakhrutdinov** [comment]
@vit-tomica, @lchudinov  shouldn't we aim the `v2.x/staging` branch?

**Comment by ifakhrutdinov** [comment]
Additionally, at some point in the future we may want to stop creating new versions of this function like this (it's already v7!) and look at some other solutions. Maybe something like the builder pattern?

**Comment by vit-tomica** [comment]
@ifakhrutdinov I don't know if we should aim for v2.x/staging branch. Who could know that?

**Comment by ifakhrutdinov** [comment]
@1000TurquoisePogs, do we merge such features to v2 only?

**Comment by anton-brezina** [comment]
Concerning the conversation above, let me emphasize, that if this does go into v2 only we'll have an ongoing defect in v1 in SAF IDT.

**Pull request merged**
